# Generated by Django 5.0.3 on 2024-04-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='email',
            field=models.EmailField(default='abc123@gmai.com', max_length=254),
        ),
    ]
